### ISSUE TITLE
Setup code coverage

### ISSUE THREAD

**Issue by lcsrinaldi** [picter/prisma#23]

**Comment by lcsrinaldi** [comment]
Also closes #16

**Comment by noxan** [comment]
Glad you linked the other issue here, but not sure how this issue should close the other? I closed the other since the changes are already in master

**Comment by lcsrinaldi** [comment]
@noxan I've included a lint step into this PR https://github.com/picter/prisma/pull/28/files#diff-1d37e48f9ceff6d8030570cd36286a61R42
