### ISSUE TITLE
Add documentation about using grid-styled system

### ISSUE THREAD

**Issue by lcsrinaldi** [picter/prisma#27]
Following up discussion from #25 

Now that there's a grid system library integrated we should document it here instead of on our Storybook, since it's not going to be exported for use in our applications.

**Comment by noxan** [comment]
Maybe it is sufficient to link to the official docs? At least the ones linked on the storybook looked quite good to me.

**Comment by lcsrinaldi** [comment]
Yes! This issue is basically remove the `Grid > Documentation` part of Storybook and insert it in the Github docs.
