### ISSUE TITLE
Define project structure 

### ISSUE THREAD

**Issue by lcsrinaldi** [picter/prisma#3]
Define a better project structure for:
- Components
- Content (like images, design guidelines, website related)
- Layouts
- ...etc...

**Comment by lcsrinaldi** [comment]
I propose the following structure:
```
project
|- src
  |- components
  |- layouts
  |- themes
  |- utils
|- stories
  |- ...
```

**Comment by noxan** [comment]
Looks good to me. Just asking: Do you think a `config` folder works? I mean most tools expect them at a specific position, most of them in the root folder?

**Comment by lcsrinaldi** [comment]
@noxan no hard feelings, I just took it by example from https://github.com/carbon-design-system/carbon-components-react, but we can do it on demand, since we still don't have so many configuration files.

**Comment by noxan** [comment]
If we have config files to put in there, I agree it makes sense. But in the end must config files end up in the repository directly, like `.storyboard`, `.eslintrc`, `.stylintrc`, etc.

**Comment by lcsrinaldi** [comment]
Yes, let's do it on demand then, if it's necessary.

So for now we agree on:

```
project
|- src
  |- components
  |- layouts
  |- themes
  |- utils
|- stories
  |- ...
```

?

**Comment by mattii** [comment]
Looks good! One last question: What about putting stories next to the components itself, like test-files. E.g. 

```
|- src
  |- components
    |- Button
      |- index.js
      |- index.spec.js
      |- index.stories.js
```

After more than a year of having tests in a separate folder in the backend, I really like the simplicity of putting them next to the tested files (it's easier to setup, to navigate, to find and to refactor).

**Comment by lcsrinaldi** [comment]
@mattii as we talked before, it's already structured this way, thanks for pointing it out otherwise I'd forget to put it in the documentation :). See connected PR to check the changes.
