### ISSUE TITLE
Add release-step to circle-ci config

### ISSUE THREAD

**Issue by mattii** [picter/prisma#37]
Example: https://github.com/picter/torii/blob/master/.circleci/config.yml

**Comment by lcsrinaldi** [comment]
If you want some inspiration https://sbstjn.com/boilerplate-for-typescript-npm-package-with-circleci-v2-workflows.html  his workflow seems pretty cool

**Comment by lcsrinaldi** [comment]
Just be aware that I've removed this line https://github.com/picter/torii/blob/master/package.json#L10 from Prisma. Since we publish our package already with the `dist/build` folder I don't see the reason to run build everytime we execute install.

**Comment by mattii** [comment]
Sure! Actually, I would prefer to release *torii* as source only. Don't know if this is possible for *prisma*, too.
