### ISSUE TITLE
Define guidelines to components

### ISSUE THREAD

**Issue by lcsrinaldi** [picter/prisma#41]
While I'm developing components for Prisma I've stumbled on some questions about folder and component structure, naming and other.

1 - Should we name styled components a different way?
2 - Should we store styled components in a different file from the exported and whole component?
3 - \<add your question here\>

---

### Definition of Done

- [ ] Refer to discussion below and write a structure section on Prisma README file.

**Comment by lcsrinaldi** [comment]
I searched around some projects, I liked how this one structured its components, although we don't need so much overhead we can make it simpler.

https://github.com/bcrumbs/reactackle/tree/master/packages/reactackle-header/src

**Comment by lcsrinaldi** [comment]
To exemplify, I did the same with our Icon component.

*Icon/index.js*
```javascript
import IconStyled from './index.styled'; // if only one styled component
import { IconStyled } from './index.styled'; // if more than one styled component

const Icon = ({ type, className, ...otherProps }) => (
  <IconStyled {...otherProps} className={classNames('material-icons', className)}>
    {type}
  </IconStyled>
);

Icon.propTypes = {
  id: PropTypes.string,
  className: PropTypes.string,
  size: PropTypes.oneOf(['inherit', 'x-small', 'small', 'medium', 'large', 'x-large']),
  color: PropTypes.string,
  type: PropTypes.string.isRequired,
};

Icon.defaultProps = {
  id: null,
  className: null,
  size: 'inherit',
  color: null,
};

export default Icon;
```

*Icon/index.styled.js* or *Icon/index.style.js* or *Icon/index.styles.js* (to be decided)
```javascript
const IconStyled = styled.i`
  vertical-align: middle;
  padding-bottom: 4px;
  color: ${props => props.color};
  font-size: 36px; 
`;

export default IconStyled;
```

Bear in mind that this is a simple component, so may it's too much for it, but for more complex ones I think it's a good idea to have more structure.

**Comment by gneutzling** [comment]
As we discussed in the call, I really liked the structure of Prisma. Also I am totally fine with `styled` component in a new file because it's better in terms of readability.

**Comment by marcuscaum** [comment]
Agree with @gneutzling, the structure really looks good!
And +1 for the styled component in a new file.picter

**Comment by mattii** [comment]
I like it, too! :+1:

**Comment by lucasfs7** [comment]
I like this pattern too... the only thing is that I think we should have only one patter for export, if we always export named consts, adding/removing things will not affect where it's using. Because if one is a default export and need to have a new export then every place where it's being imported must change

**Comment by lcsrinaldi** [comment]
I agree with @lucasfs7 that we must have a standard for this. Although, I don't know if I understood what you mean. I feel it's the same for named and default.

With default export:
```javascript
import Default from './example-file';
// adding a new export
import Default, { DefaultStyled } from './example-file';
```

With named export:
```javascript
import { Default } from './example-file';
// adding a new export
import { Default, DefaultStyled } from './example-file';
```

The standard that I'm currently using is exporting default the main functionality of the file, if there's one. Otherwise use named, like for utilities.

**Comment by lucasfs7** [comment]
@lcsrinaldi you're right, they aren't too different at the end

**Comment by lcsrinaldi** [comment]
@noxan , I think that you've expressed some concerns against using `index.styled`. Would you find this structure here better? https://github.com/bcrumbs/reactackle/tree/master/packages/reactackle-header/src

**Comment by olarclara** [comment]
LGTM. 🚀

**Comment by noxan** [comment]
<img width="279" alt="screen shot 2017-12-22 at 18 13 50" src="https://user-images.githubusercontent.com/536225/34306536-0667085c-e744-11e7-80c9-25bc48ef9ae0.png">

credits to @lucasfs7

**Comment by noxan** [comment]
LGTM.
