### ISSUE TITLE
Fix "No 'Access-Control-Allow-Origin'" for fonts on Storybook Github page

### ISSUE THREAD

**Issue by lcsrinaldi** [picter/prisma#86]
![image](https://user-images.githubusercontent.com/1268808/34105165-6da323ce-e3da-11e7-810d-5a50b45abc38.png)

**Comment by mattii** [comment]
I canged the CORS config to allow GET-requests from `picter.github.io`. It's possible, that the rejection is still cached, but it should work within an our.

**Comment by lcsrinaldi** [comment]
It's working, thanks for your help Matti :)
